/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_code22_mtrade_NativeCallsClass */

#include <stddef.h>
#include <stdio.h>

#include "libjpeg/jpeglib.h"
#include "libjpeg/jerror.h"

#ifndef _Included_ru_code22_mtrade_NativeCallsClass
#define _Included_ru_code22_mtrade_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_code22_mtrade_NativeCallsClass
 * Method:    convertJpegFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BIIIII)V
 */
JNIEXPORT jint JNICALL Java_ru_code22_mtrade_NativeCallsClass_convertJpegFile
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
